# Default namespace. Override with your own
namespace: monitoring
resources:
  - ingress.yaml
  # Prometheus
  - prometheus-sts.yaml
  - prometheus-svc.yaml
  - prometheus-env.yaml
  - prometheus-rbac.yaml
  # Alertmanager
  - alertmanager-sts.yaml
  - alertmanager-svc.yaml
  # Grafana
  - grafana-sts.yaml
  - grafana-svc.yaml
  # Node Exporter
  - node-exporter-ds.yaml
  # Blackbox Exporter
  - blackbox-exporter-deployment.yaml
  - blackbox-exporter-svc.yaml
  # kube-state-metrics
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-rbac.yaml
  - kube-state-metrics-service.yaml
configMapGenerator: 
  - name: prometheus-configmap
    files:
      - prometheus.yml
  - name: blackbox-targets
    files:
      - blackbox-targets.yml
  - name: alertmanager
    files:
      - alertmanager.yml
  - name: blackbox-exporter
    files:
      - blackbox.yaml
  - name: prometheus-rules
    files: 
      - prometheus-rules/load-average.rules.yml
      - prometheus-rules/blackbox.rules.yml
  - name: alertmanager-templates
    files:
      - alertmanager-templates/default.tmpl
      - alertmanager-templates/slack.tmpl
# In general, adding hashes to the name suffix is a good thing. Restarting is a relatively intrusive operation for Prometheus, however, and live-reloading is supported.
generatorOptions:
  disableNameSuffixHash: true
