# Default namespace. Override with your own
namespace: monitoring
resources:
  # Prometheus
  - prometheus-sts.yaml
  - prometheus-svc.yaml
  - prometheus-env.yaml
  - prometheus-rbac.yaml
  # Alertmanager
  - alertmanager-sts.yaml
  - alertmanager-configmap.yaml
  - alertmanager-svc.yaml
  # Grafana
  - grafana-sts.yaml
  - grafana-svc.yaml
  # Node Exporter
  - node-exporter-ds.yaml
  - ingress.yaml
  # kube-state-metrics
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-rbac.yaml
  - kube-state-metrics-service.yaml
configMapGenerator: 
  - name: prometheus-configmap
    files:
      - prometheus.yml
  - name: prometheus-rules
    files: 
      - prometheus-rules/load-average.rules.yml
  - name: alertmanager-templates
    files:
      - alertmanager-templates/default.tmpl
      - alertmanager-templates/slack.tmpl
generatorOptions:
  disableNameSuffixHash: true
