apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-prometheus
rules:
- apiGroups:
  - ""
  resources:
  # This set of resources is every target "role" that Prometheus supports. 
  # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config
  - nodes
  - pods
  - services
  - endpoints
  - ingress
  verbs:
  - get
  - list
  - watch
