#!/usr/bin/env python3

DESCRIPTION = (
        "rules2k8s converts standard Prometheus rules into "
        "Prometheus-Operator's `monitoring.coreos.com/v0/PrometheusRule` "
        "objects.'"
        )

import argparse
import fileinput
import sys
import yaml
from copy import deepcopy

templateobj = {'apiVersion': 'monitoring.coreos.com/v1',
 'kind': 'PrometheusRule',
 'metadata': {
     'labels': {},
     'name': '',
 },
 'spec': {},
}


def main():
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    parser.add_argument("--comment", default = "AUTOGENERATED BY rules2k8s", help="Comment to include at the begginning of output")
    parser.add_argument("--namespace", "-n", help="If set, include a namespace in the metadata")
    parser.add_argument("files", nargs='*', default = ["-"], help="list of filenames (defaults to stdin)")

    args = parser.parse_args()

    if args.namespace:
        templateobj['metadata']['namespace'] = args.namespace

    
    print("#", args.comment)

    for rulesfilename in args.files:
        with (rulesfilename == "-" and sys.stdin) or open(rulesfilename) as rulesfile:
            rulesobj = yaml.safe_load(rulesfile)

        k8sobj = deepcopy(templateobj)
        k8sobj["metadata"]["name"] = rulesfilename
        k8sobj["spec"] = rulesobj

        print(yaml.dump(k8sobj))

if __name__ ==  "__main__":
    main()
